
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: persoanl_portfolio_development

test:
  <<: *default
  database: persoanl_portfolio_test


production:
  <<: *default
  database: persoanl_portfolio_production
  username: persoanl_portfolio
  password: <%= ENV['PERSOANL_PORTFOLIO_DATABASE_PASSWORD'] %>
